-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "date1" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "date1" SET DATA TYPE DATE,
ALTER COLUMN "date2" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "date2" SET DATA TYPE DATE,
ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "updatedAt" SET DEFAULT NOW();
