-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "date1" DROP DEFAULT,
ALTER COLUMN "date1" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "date2" DROP DEFAULT,
ALTER COLUMN "date2" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "updatedAt" SET DEFAULT NOW();
