-- AlterTable
ALTER TABLE "Comment" ADD COLUMN     "createdAt" TIMESTAMP(0) NOT NULL DEFAULT NOW(),
ADD COLUMN     "updatedAt" TIMESTAMP(0) NOT NULL DEFAULT NOW();

-- AlterTable
ALTER TABLE "Image" ADD COLUMN     "createdAt" TIMESTAMP(0) NOT NULL DEFAULT NOW(),
ADD COLUMN     "updatedAt" TIMESTAMP(0) NOT NULL DEFAULT NOW();

-- AlterTable
ALTER TABLE "Like" ADD COLUMN     "createdAt" TIMESTAMP(0) NOT NULL DEFAULT NOW();

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "createdAt" SET DEFAULT NOW(),
ALTER COLUMN "updatedAt" SET DEFAULT NOW();

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(0) NOT NULL DEFAULT NOW(),
ADD COLUMN     "updatedAt" TIMESTAMP(0) NOT NULL DEFAULT NOW();
